services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  flower:
    image: mher/flower
    command: celery --broker=${CELERY_BROKER_URL:-redis://redis/0} flower
    ports:
      - 5555:5555
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL:-redis://redis/0}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND:-redis://redis/0}
    depends_on:
    - redis
